{
    'name': 'Edafaa Student Profile',
    'version': '19.0.2.6.0',
    'post_init_hook': 'post_init_hook',
    'category': 'Education',
    'summary': 'Student profile enhancements for Edafaa / OpenEduCat SIS',
    'depends': [
        'openeducat_core',
        'openeducat_parent',
        'openeducat_admission',
        'mail',
        'sales_team',
    ],
    'external_dependencies': {
        'python': ['openpyxl'],
    },
    'data': [
        'security/ir.model.access.csv',
        'data/course_sequence.xml',
        'data/program_sequence.xml',
        'data/certificate_sequence.xml',
        'reports/certificate_report.xml',
        'data/mail_template.xml',
        'views/skill_views.xml',
        'views/course_views.xml',
        'views/program_views.xml',
        'views/certificate_views.xml',
        'views/student_views.xml',
        'views/student_search_views.xml',
        'views/admission_views.xml',
        'wizard/trainee_sales_assign_wizard_views.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
}
